### ISSUE TITLE
Whitelisting

### ISSUE THREAD

**Issue by Damianu** [thegrb93/StarfallEx#375]
# Todo:
- [ ] Make UI for whitelists
- [ ] Make separate permission check build for chips with requested permissions (so whitelist wont get ignored)
- [ ] Add custom whitelist saving/loading
- [ ] Add option for permission request to whitelist specific sites for that instance
# Other stuff
- [ ] Add whitelist checker for player steamids

Notes: 
- Whitelist request should require additional confirmation with scarry information ☠️ 
- Whitelist request should not support patterns (Easy to abuse)

**Comment by thegrb93** [comment]
Going to move the whitelist/blacklist stuff for holograms/sounds/rendering from 'stuff to add' to here
